name: Compilation
description: "Validates the typescript and tailwind compilation of the project"

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js and pnpm
      uses: ./.github/actions/setup-node-pnpm
      
    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
      
    - name: Run validations in parallel
      shell: bash
      run: |
        echo "Running TypeScript compilation..."
        pnpm compile &
        compile_pid=$!
        
        echo "Running Tailwind CSS compilation..."
        pnpm tailwind:build &
        tailwind_pid=$!
        
        # Wait for all processes and check their exit codes
        wait $compile_pid
        compile_exit=$?
        
        wait $tailwind_pid
        tailwind_exit=$?

        # Report results
        echo "=== Validation Results ==="
        echo "TypeScript compilation: $([ $compile_exit -eq 0 ] && echo '✓ PASSED' || echo '✗ FAILED')"
        echo "Tailwind CSS compilation: $([ $tailwind_exit -eq 0 ] && echo '✓ PASSED' || echo '✗ FAILED')"
        
        # Exit with error if any validation failed
        if [ $compile_exit -ne 0 ] || [ $tailwind_exit -ne 0 ]; then
          echo "❌ Some validations failed"
          exit 1
        fi
        
        echo "✅ All validations passed"
        
    - name: Clean up build artifacts
      run: |
        rm -f ./src/shared/styles/output.css
      if: always()
