name: PR Pipeline

on:
  pull_request:
    branches: [main, master]
    types: [opened, synchronize, reopened]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js and pnpm
        uses: ./.github/actions/setup-node-pnpm

  code-check:
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run code check
        uses: ./.github/actions/pr-code-check

  compilation:
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run compilation
        uses: ./.github/actions/pr-compilation

  build-validation:
    runs-on: ubuntu-latest
    needs: [compilation]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run build validation
        uses: ./.github/actions/pr-build
