name: PR Validation

on:
  pull_request:
    branches: [ main, master ]
    types: [ opened, synchronize, reopened ]

jobs:
  validation:
    name: Code Quality & Compilation
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
          
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8
          
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        
      - name: Run validations in parallel
        run: |
          echo "Running TypeScript compilation..."
          pnpm compile &
          compile_pid=$!
          
          echo "Running Tailwind CSS compilation..."
          pnpm tailwind:build &
          tailwind_pid=$!
          
          echo "Running lint check..."
          pnpm lint &
          lint_pid=$!
          
          echo "Running format check..."
          pnpm format:check &
          format_pid=$!
          
          # Wait for all processes and check their exit codes
          wait $compile_pid
          compile_exit=$?
          
          wait $tailwind_pid
          tailwind_exit=$?
          
          wait $lint_pid
          lint_exit=$?
          
          wait $format_pid
          format_exit=$?
          
          # Report results
          echo "=== Validation Results ==="
          echo "TypeScript compilation: $([ $compile_exit -eq 0 ] && echo '✓ PASSED' || echo '✗ FAILED')"
          echo "Tailwind CSS compilation: $([ $tailwind_exit -eq 0 ] && echo '✓ PASSED' || echo '✗ FAILED')"
          echo "Lint check: $([ $lint_exit -eq 0 ] && echo '✓ PASSED' || echo '✗ FAILED')"
          echo "Format check: $([ $format_exit -eq 0 ] && echo '✓ PASSED' || echo '✗ FAILED')"
          
          # Exit with error if any validation failed
          if [ $compile_exit -ne 0 ] || [ $tailwind_exit -ne 0 ] || [ $lint_exit -ne 0 ] || [ $format_exit -ne 0 ]; then
            echo "❌ Some validations failed"
            exit 1
          fi
          
          echo "✅ All validations passed"
          
      - name: Clean up build artifacts
        run: |
          rm -f ./src/shared/styles/output.css
        if: always()

  build-test:
    name: Build Validation
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
          
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8
          
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        
      - name: Build library
        run: pnpm build
        
      - name: Verify build
        run: |
          echo "Verifying build artifacts..."
          ls -la dist/
          
          # Check required files
          for file in index.js index.d.ts server.js api.js; do
            if [ -f "dist/$file" ]; then
              echo "✓ Found dist/$file"
            else
              echo "✗ Missing dist/$file"
              exit 1
            fi
          done
          
          echo "✅ Build validation completed successfully"